config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/cards/new', to: 'cards#new'
  post '/cards/new', to: 'cards#create'
  get '/cards/edit', to: 'cards#edit'
  patch '/cards/update', to: 'cards#update'

  post '/twilio', to: 'twilio#text'

  resources :customers, except: [:index]

  resources :tabs do
    resources :items, only: [:create, :show, :destroy]
  end

  resources :businesses, only: [:show]
  get '/dashboard', to: 'dashboard#index'

  get '/tabs/:id/checkout', to: 'tabs#checkout', as: 'checkout_tab'
  post '/tabs/:id/close', to: 'tabs#close', as: 'close_tab'
end

app/models/tab.rb
class Tab < ApplicationRecord
  belongs_to :customer
  belongs_to :business
  has_many :items, dependent: :destroy
  validates :customer_id, :business_id, presence: true
  # validate :customer_one_open_tab_at_bar

  def total_price
    sub = self.items.reduce(0) { |total, item| total + item.price }
  end

  def is_open?
    self.transaction_id == nil
  end

  # def customer_one_open_tab_at_bar
  #   business = self.business
  #   match = business.tabs.find_by(business_id: self.business_id, customer_id: self.customer_id)
  #   p match.is_open?
  #   if match && match.is_open?
  #     errors.add(:unique, "You already have an open tab with this bar")
  #   end
  # end
end

app/controllers/tabs_controller.rb
class TabsController < ApplicationController
  include TabsHelper
  def index
    redirect_to root_path and return if !logged_in?
    if session[:user_type] == 'Business'
      @business = current_user
    end
    @tabs = current_user.closed_tabs
  end

  def new
    redirect_to root_path and return if !logged_in?
    @tab = Tab.new
  end

  def create
    limit_amount = params[:limit_amount]
    limit_cost = params[:limit_cost]

    @business = Business.find_by(username: params[:username].downcase)
    if @business
      open_tabs = @business.open_tabs
      @tab = Tab.find_or_initialize_by(business_id: @business.id, customer_id: current_user.id, transaction_id: nil)
      if open_tabs.include?(@tab)
        @errors = ['It looks like you already have an open tab with this bar. Please navigate to your open tabs to order a drink or close your previous tab']
        render 'new'
      else

        @tab.limit_cost = params[:limit_cost]
        @tab.limit_amount = params[:limit_amount]

        if @tab.save
          redirect_to tab_path(@tab)
        else
          @errors = ['The handle entered does not belong to any bar - please confirm it was entered correctly']
          render 'new'
        end
      end
    else
      @errors = ['The handle entered does not belong to any bar - please confirm it was entered correctly']
      render 'new'
    end
  end

  def show
    redirect_to root_path and return if !logged_in? || params[:id].to_i > Tab.last.id
    @tab = Tab.find(params[:id])
    redirect_to root_path and return if session[:user_id] != @tab.customer_id && session[:user_id] != @tab.business_id
    @item = Item.new
    render 'show'
  end

  def checkout
    # redirect_to root_path and return if !logged_in? || params[:id].to_i > Tab.last.id
    @tab = Tab.find(params[:id])
    # redirect_to root_path and return if session[:user_id] != @tab.customer_id && session[:user_id] != @tab.business_id
    @client_token = CreditCardService.new(customer: @tab.customer).generate_token(vault_id: @tab.customer.vault_id)
    render 'checkout'
  end

  def destroy
    @tab = Tab.find(params[:id])
    customer = Customer.find(@tab.customer_id)
    if customer.id == current_user.id
      @tab.destroy!
      flash[:notice] = "Your tab at #{@tab.business.dba} was deleted successfully!".html_safe
      redirect_to customer_path(customer)
    else
      redirect_to root_path
    end
  end

  def close
    @tab = Tab.find(params[:id])
    @customer = @tab.customer
    sub_total = @tab.total_price
    tip_percentage = params[:close][:tip].to_i
    tip = sub_total * tip_percentage / 100
    total =  tip + sub_total
    result = CreditCardService.new(customer: @tab.customer).create_transaction(total)
    @tab.transaction_id = result.transaction.id
    @tab.tip = tip
    if @tab.save
      if session[:user_type] == 'Customer'
        @transaction = true
        @recent_tabs = @customer.tabs.order("updated_at DESC").limit(3)
        @open_tabs = @customer.tabs.where(transaction_id: nil)
        render '/customers/show'
      else
        business_name = @tab.business.dba
        TextMessageService.new({text_number: @tab.customer.phone, text_body: "Notice:\n#{business_name} closed your tab.\nSubtotal: $#{price_in_dollars(sub_total)}\nTip: $#{price_in_dollars(tip)}\nTotal: $#{price_in_dollars(total)}"}).send_text
        redirect_to @tab.business
      end
    else
      if session[:user_type] == 'Customer'
        @transaction = false
        render 'show'
      else
        redirect_to @tab.business
      end
    end
  end
end

app/helpers/tabs_helper.rb
module TabsHelper
  def price_in_dollars(price)
    dollars = price/100
    cents = price%100
    if cents < 10
      cents = "0#{cents}"
    end
    "#{dollars}.#{cents}"
  end
end

app/views/tabs/_tab.html.erb
<% if @business %>
<a href="/tabs/<%= tab.id %>" class="tab-list-item">
  <li class="list-group-item justify-content-between">
    <span class="tab-title"><%= "@#{tab.customer.username}" %></span>
    <br>
    <span class="faded tab-time-stamp">
      <%= if tab.is_open? then "Opened " + time_ago_in_words(tab.created_at) + " ago" else "Closed " + time_ago_in_words(tab.updated_at) + " ago" end %>
    </span>
    <span class="badge <%= "open-tab" if tab.is_open? %>">
      $<%= price_in_dollars(tab.total_price + tab.tip) %>
    </span>
  </li>
</a>
<% else %>
<a href="/tabs/<%= tab.id %>" class="tab-list-item">
  <li class="list-group-item justify-content-between">
    <span class="tab-title"><%= tab.business.dba %></span>
    <br>
    <span class="faded tab-time-stamp">
      <%= if tab.is_open? then "Opened " + time_ago_in_words(tab.created_at) + " ago" else "Closed " + time_ago_in_words(tab.updated_at) + " ago" end %>
    </span>
    <span class="badge <%= "open-tab" if tab.is_open? %>">
      $<%= price_in_dollars(tab.total_price + tab.tip) %>
    </span>
  </li>
</a>
<% end %>

app/views/tabs/_table_businesses.html.erb
<h1>@<%= @tab.customer.username %></h1>

<% if @tab.is_open? %>
  <p class="tab-timestamp">Opened <%= time_ago_in_words(@tab.created_at) %> ago</p>
<% else %>
  <p class="tab-timestamp">Closed <%= time_ago_in_words(@tab.updated_at) %> ago</p>
<% end %>
<hr>
<% if @tab.is_open? %>
  <%= form_for [@tab, @item], class: "form-inline" do |f| %>

  <%= f.label :drink_type, 'Drink' %>
  <%= f.select(:drink_type, {}, {}, class: "form-control") do %>
    <% [['-select-', ''],['Beer', 'Beer'], ['Wine', 'Wine'], ['Cocktail', 'Cocktail'], ['Shot/Liquor', 'Shot/Liquor'],].each do |c| %>
      <%= content_tag(:option, c.first, value: c.last) %>
    <% end %>
  <% end %>
    <%= f.label 'Price ($)' %>
    <%= f.text_field :price, class: "form-control" %>
    <%= f.submit 'Add', class: "btn btn-success submit-new-drink" %>
  <% end %>
<% end %>

<% if @tab.items.any? %>
  <table class="table table-striped table-hover" id="tab-table">
    <thead>
      <tr class='row-darker'>
        <th>#</th>
        <th>Item</th>
        <th>Price</th>
        <% if @tab.is_open? %>
          <th>Action</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @tab.items.each_with_index do |item, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= item.drink_type %></td>
          <td>$<%= price_in_dollars(item.price) %></td>

          <% if @tab.is_open? %>
            <td><%= link_to 'Delete',
                 tab_item_path(@tab, item),
                        method: :delete,
                        data: { confirm: 'Are you sure you want to delete this drink?' },
                        class: "delete-item" %>
            </td>
          <% end %>
        <% end %>
        </tr>
      <tr class='row-darker'>
        <td>-</td>
        <td>Subtotal</td>
        <td>$<%= price_in_dollars(@tab.total_price) %></td>
        <% if @tab.is_open? %>
          <td><%= link_to 'Checkout', checkout_tab_path, class: "btn btn-success checkout-btn" %></td>
        <% end %>
      </tr>

      <% if !@tab.is_open? %>
      <tr>
        <td>-</td>
        <td>Tip</td>
        <td>$<%= price_in_dollars(@tab.tip) %></td>
      </tr>
      <tr class ='row-darker'>
        <td>-</td>
        <td>Total</td>
        <td>$<%= price_in_dollars(@tab.total_price + @tab.tip) %> </td>
      <% end %>
      </tr>
    </tbody>
  </table>
<% else %>
  <li id='no-orders' class='btn btn-default'>No items have been ordered.</li>
<% end %>

<% if !@tab.is_open? %>
  <button class="btn btn-inactive full-width">Tab Closed</button>
<% end %>

app/views/tabs/_table_customers.html.erb
<% if @tab.is_open? %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button> Use <strong>@<%= @tab.customer.username %></strong> at the bar to add items to your tab.
  </div>
<% end %>
  <h1><%= name(@tab.business) %></h1>

<% if @tab.is_open? %>
  <p class="tab-timestamp">Opened <%= time_ago_in_words(@tab.created_at) %> ago</p>
<% else %>
  <p class="tab-timestamp">Closed <%= time_ago_in_words(@tab.updated_at) %> ago</p>
<% end %>
<hr>
<% if @tab.items.any? %>
  <table class="table table-striped table-hover" id="tab-table">
    <thead>
      <tr class='row-darker'>
        <th>#</th>
        <th>Item</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <% @tab.items.each_with_index do |item, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= item.drink_type %></td>
          <td>$<%= price_in_dollars(item.price) %></td>
      <% end %>
        </tr>
      <tr class='row-darker'>
        <td>-</td>
        <td>Subtotal</td>
        <td>$<%= price_in_dollars(@tab.total_price) %></td>
      </tr>

    <% if !@tab.is_open? %>
      <tr>
        <td>-</td>
        <td>Tip</td>
        <td>$<%= price_in_dollars(@tab.tip) %></td>
      </tr>
      <tr class ='row-darker'>
        <td>-</td>
        <td>Total</td>
        <td>$<%= price_in_dollars(@tab.total_price + @tab.tip) %> </td>
      </tr>
      <% end %>
    </tbody>
  </table>
   <hr class="bad-hr">
<% else %>
    <li id='no-items-error' class='btn btn-default'>No items have been ordered.</li>
    <hr class="bad-hr">
<% end %>

<% if @tab.is_open? && @tab.items.empty? %>
    <%= link_to 'Delete Tab', tab_path(@tab), method: :delete,
      data: { confirm: 'Are you sure you want to delete this tab?' }, class: "btn delete-tab" %>
<% elsif @tab.is_open? %>
    <%= button_to "Checkout", checkout_tab_path, method: :get, class: "btn btn-primary full-width" %>
<% else %>
    <button class="btn btn-inactive full-width">Tab Closed</button>
<% end %>

app/views/tabs/checkout.html.erb
<%= link_to '<i class="fa fa-angle-double-left" aria-hidden="true"></i>'.html_safe, @tab, class: 'navigation' %>

<h3 class="checkout-label">Checkout from:</h3>
<h2><strong><%= name(@tab.business) %></strong></h2>
<hr>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <td>Subtotal</td>
      <td>$<%= price_in_dollars(@tab.total_price) %></td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Tip</td>
      <td id="tip-price-checkout">$0.00</td>
    </tr>
    <tr class='row-darker'>
      <th>Total</th>
      <th id="total-price-checkout">$<%= price_in_dollars(@tab.total_price) %></th>
    </tr>
  </tbody>
</table>
<hr>
<h3>Choose your tip:</h3>
<%= form_for :close, url: close_tab_path, html: { class: "radio-buttons-checkout full-width container", id: 'close-tab' } do |f| %>
  <%= f.hidden_field :nonce %>
  <%= f.radio_button :tip, '0', style: 'display:none' %>
  <%= f.radio_button :tip, '10', style: 'display:none' %>
  <%= f.radio_button :tip, '15', style: 'display:none' %>
  <%= f.radio_button :tip, '20', style: 'display:none' %>
  <div class="row">
  <div class="btn-group full-width container">
    <%= label :close_tip, '0', '0%', class: "btn btn-default col-xs-3 active label-click" %>
    <%= label :close_tip, '10', '10%', class: "btn btn-default col-xs-3 label-click" %>
    <%= label :close_tip, '15', '15%', class: "btn btn-default col-xs-3 label-click"%>
    <%= label :close_tip, '20', '20%', class: "btn btn-default col-xs-3 label-click" %>
  </div>
  </div>
  <div id="dropin-container"></div>
  <%= f.submit 'Tab Out', class: "full-width btn btn-primary margin-top" %>
<% end %>

<script src="https://js.braintreegateway.com/web/dropin/1.4.0/js/dropin.min.js"></script>
<script>
  var button = document.querySelector("input[type='submit']");
  var form = document.querySelector('form#close-tab');

  braintree.dropin.create({
    authorization: '<%= @client_token %>',
    container: '#dropin-container'
  }, function (createErr, instance) {
    button.addEventListener('click', function (event) {
      event.preventDefault();
      instance.requestPaymentMethod(function (requestPaymentMethodErr, payload) {
        var nonce = form.querySelector('#close_nonce')
        nonce.value = payload.nonce;
        form.submit();
      });
    });
  });
</script>

app/views/tabs/index.html.erb
<%= link_to '<i class="fa fa-angle-double-left" aria-hidden="true"></i>'.html_safe, root_path, class: 'navigation' %>

<h1>History</h1>
<h4 class="settings-username">@<%= current_user.username %></h4>
<hr>
<ul class="list-group">
  <% if !@tabs.empty? %>
    <%= render @tabs %>
  <% else %>
    <li id="no-items-error" class="btn btn-default">You have no tabs in your history.</li>
  <% end %>
</ul>

app/views/tabs/new.html.erb
<%= link_to '<i class="fa fa-angle-double-left" aria-hidden="true"></i>'.html_safe, :back, class: 'navigation' %>

<h1>Where are you?</h1>
<%= form_tag('/tabs', method:'post') do %>
  <%= label :username, "Bar" %>
  <div class="input-group" id="bar-lookup">
    <span class="input-group-addon" id="basic-addon2">@</span>
    <%= text_field_tag(:username, nil, placeholder: '',  class: "form-control", autofocus: true) %>
  </div>

  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    We encourage users to set <strong>limits</strong> below - you will receive a text from TabOut once your tab reaches your chosen limits.
  </div>

  <ul class="nav nav-tabs">
    <li class="active col-xs-6 limit-tabs"><a data-toggle="tab" href="#amount">Number of Drinks</a></li>
    <li class="col-xs-6 limit-tabs"><a data-toggle="tab" href="#cost">Total Cost</a></li>
  </ul>
  <div class="tab-content">

    <%= label :limit, "Limit", class: "limit-label" %>
    <div id="amount" class="tab-pane fade in active">
      <%= select_tag(:limit_amount, options_for_select([['No limit', '0'],['1', '1'], ['2', '2'], ['3', '3'], ['4', '4'], ['5', '5'], ['6', '6']], current_user.limit_amount), class: "form-control full-width limit-dropdown") %>
    </div>

    <div id="cost" class="tab-pane fade in">
        <%= select_tag(:limit_cost, options_for_select([['No limit', '0'],['$10', '1000'], ['$20', '2000'], ['$30', '3000'], ['$40', '4000'], ['$50', '5000'], ['$60', '6000']], current_user.limit_cost), class: "form-control full-width limit-dropdown") %>
    </div>
  </div>
  <hr>

  <%= submit_tag("Open Tab", id: 'open-tab', class: "btn btn-primary full-width") %>
<% end %>

app/views/tabs/show.html.erb
<% if @tab.is_open? %>
<%= link_to '<i class="fa fa-angle-double-left" aria-hidden="true"></i>'.html_safe, root_path, class: 'navigation' %>
<% else %>
<%= link_to '<i class="fa fa-angle-double-left" aria-hidden="true"></i>'.html_safe, tabs_path, class: 'navigation' %>
<% end %>

<% if session[:user_type] == 'Customer' %>
  <%= render partial: 'table_customers' %>
<% elsif session[:user_type] == "Business" %>
  <%= render partial: 'table_businesses' %>
<% end %>