config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/cards/new', to: 'cards#new'
  post '/cards/new', to: 'cards#create'
  get '/cards/edit', to: 'cards#edit'
  patch '/cards/update', to: 'cards#update'

  post '/twilio', to: 'twilio#text'

  resources :customers, except: [:index]

  resources :tabs do
    resources :items, only: [:create, :show, :destroy]
  end

  resources :businesses, only: [:show]
  get '/dashboard', to: 'dashboard#index'

  get '/tabs/:id/checkout', to: 'tabs#checkout', as: 'checkout_tab'
  post '/tabs/:id/close', to: 'tabs#close', as: 'close_tab'
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def new
    redirect_to root_path and return unless logged_in?
    @client_token = CreditCardService.new().generate_token()
  end

  def create
    @customer = current_user

    payment_params = params[:card]
    result = CreditCardService.new({customer: @customer}).create_customer(payment_params)

    if result.success?
      @customer.vault_id = result.customer.id
      @customer.save
      redirect_to root_url
    else
      @errors = ["Card is not valid - please check that it was submitted correctly"]
      @client_token = CreditCardService.new().generate_token()
      render '/cards/new'
    end
  end

  def edit
    redirect_to root_path and return unless logged_in?
    @client_token = CreditCardService.new(customer: current_user).generate_token(vault_id: current_user.vault_id)
  end
end

app/views/cards/edit.html.erb
<%= link_to '<i class="fa fa-angle-double-left" aria-hidden="true"></i>'.html_safe, :back, class: 'navigation' %>

<h2>Add a New Card</h2>

<div id="dropin-container"></div>

<%= form_for :card, url: cards_edit_path, method: :get, html:{ id: 'edit-cards' } do |f| %>
   <%= f.hidden_field :nonce %><br />
   <%= f.submit 'Add Card', class: 'btn btn-primary full-width' %><br />
 <% end %>

<script src="https://js.braintreegateway.com/web/dropin/1.4.0/js/dropin.min.js"></script>
<script>
  var button = document.querySelector("input[type='submit']");
  var form = document.querySelector('form#edit-cards');

  braintree.dropin.create({
    authorization: '<%= @client_token %>',
    container: '#dropin-container'
  }, function (createErr, instance) {
    button.addEventListener('click', function (event) {
      event.preventDefault();
      instance.requestPaymentMethod(function (requestPaymentMethodErr, payload) {
        var nonce = form.querySelector('input[name="card[nonce]"]')
        form.querySelector('input[name="card[nonce]"]').value = payload.nonce;
      });
    });
  });
</script>

app/views/cards/new.html.erb
<%= link_to '<i class="fa fa-angle-double-left" aria-hidden="true"></i>'.html_safe, :back, class: 'navigation' %>

<h2>Add a card</h2>

<div id="dropin-container"></div>

<%= form_for :card html:{ id: 'new-card' }do |f| %>
   <%= f.hidden_field :nonce %><br />
   <%= f.submit 'Add Card', class: 'btn btn-primary full-width' %><br />
 <% end %>

<script src="https://js.braintreegateway.com/web/dropin/1.4.0/js/dropin.min.js"></script>
<script>
  var button = document.querySelector("input[type='submit']");
  var form = document.querySelector('form#new-card');

  braintree.dropin.create({
    authorization: '<%= @client_token %>',
    container: '#dropin-container'
  }, function (createErr, instance) {
    button.addEventListener('click', function (event) {
      event.preventDefault();
      instance.requestPaymentMethod(function (requestPaymentMethodErr, payload) {
        var nonce = form.querySelector('input[name="card[nonce]"]')
        form.querySelector('input[name="card[nonce]"]').value = payload.nonce;
        form.submit();
      });
    });
  });
</script>