config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/cards/new', to: 'cards#new'
  post '/cards/new', to: 'cards#create'
  get '/cards/edit', to: 'cards#edit'
  patch '/cards/update', to: 'cards#update'

  post '/twilio', to: 'twilio#text'

  resources :customers, except: [:index]

  resources :tabs do
    resources :items, only: [:create, :show, :destroy]
  end

  resources :businesses, only: [:show]
  get '/dashboard', to: 'dashboard#index'

  get '/tabs/:id/checkout', to: 'tabs#checkout', as: 'checkout_tab'
  post '/tabs/:id/close', to: 'tabs#close', as: 'close_tab'
end

app/views/layouts/_errors.html.erb
<% if @errors %>
<% p @errors %>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <% @errors.each do |error| %>
      <p><%= error %>.</p>
      <% end %>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbarr navbarr-default full-width">
  <div class="container-fluid navbar-fill">
    <div class="navbar-header">
      <span class="nav-open" style="font-size:30px;cursor:pointer">&#9776;</span>
      <a class="brand" href="/">TabOut</a>
      <% if session[:user_type] == 'Customer' %>
        <%= form_tag(new_tab_path, method:'get', class: 'nav-form') do %>
          <%= button_tag "<i class='fa fa-glass' aria-hidden='true'></i>".html_safe, class: 'btn btn-nav'%>
        <% end %>
      <% else %>
        <%= button_tag "<i class='fa fa-glass' aria-hidden='true'></i>".html_safe, class: 'btn btn-nav hidden-button'%>  
      <% end %>
    </div>
    <div id="navbar" class="sidenav">
      <a href="javascript:void(0)" class="nav-close">&times;</a>
    <% if logged_in? %>
        <p href='#' class="nav-username"><strong>@<%= current_user.username %></strong></p>
        <hr class="nav-hr-lg">
        <%= link_to 'My Tabs', root_path %>
      <% if current_user.class == Customer %>
        <hr class="nav-hr-sm">
        <%= link_to "Settings", edit_customer_path(current_user) %>
      <% else %>
          <hr class="nav-hr-sm">
          <%= link_to 'Dashboard', dashboard_path %>
      <% end %>
        <hr class="nav-hr-sm">
        <%= link_to 'History', tabs_path %>
        <hr class="nav-hr-sm">
        <%= link_to 'Logout', logout_path %>
    <% else %>
        <hr class="nav-hr-sm">
        <%= link_to 'Sign Up', new_customer_path %>
        <hr class="nav-hr-sm">
        <%= link_to 'Login', login_path %>
    <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TabOut</title>
    <%= csrf_meta_tags %>
    <!-- Adds proper mobile rendering and prevents page zoom -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <!-- When bookmarked, removes browser frame -->
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <!-- Bookmark icons -->
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#3b3b3b">
    <meta name="theme-color" content="#292B2C">
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans|Source+Sans+Pro:900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <main class="container-wide">

      <header>
        <%= render 'layouts/nav' %>
      </header>

      <section class="container content">
        <%= render 'layouts/errors' %>

        <div class="overlay" style="display: none;"></div>
        <div id="overlay" style="display: none;"></div>
        <%= yield %>
      </section>

    </main>
  </body>
</html>